packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  prisma:
    'prisma': latest
    '@prisma/client': latest

catalog:
  'typescript': '5.9.3'
  'zod': '^4.0.0'
  'axios': '1.12.2'
  'tsup': '8.1.0'
  'dotenv': '17.2.3'
  '@tsconfig/node20': '20.1.4'
  '@types/node': '20.19.0'
