packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  prisma:
    'prisma': '6.19.0'
    '@prisma/client': '6.19.0'

catalog:
  'typescript': '5.9.3'
  'zod': '^4.0.0'
  'axios': '1.12.2'
  'tsup': '8.1.0'
  'dotenv': '17.2.3'
  '@tsconfig/node20': '20.1.4'
  'http-status-codes': '^2.3.0'
  'date-fns': '4.1.0'
  'stripe': '^20.0.0'
  '@types/node': '20.19.0'
