/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLogoutIndexRouteImport } from './routes/_auth/logout/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as appPricingIndexRouteImport } from './routes/(app)/pricing/index'
import { Route as appVerifyTokenRouteImport } from './routes/(app)/verify/$token'
import { Route as appAnalyseIdRouteImport } from './routes/(app)/analyse/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLogoutIndexRoute = AuthLogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appPricingIndexRoute = appPricingIndexRouteImport.update({
  id: '/(app)/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const appVerifyTokenRoute = appVerifyTokenRouteImport.update({
  id: '/(app)/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const appAnalyseIdRoute = appAnalyseIdRouteImport.update({
  id: '/(app)/analyse/$id',
  path: '/analyse/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse/$id': typeof appAnalyseIdRoute
  '/verify/$token': typeof appVerifyTokenRoute
  '/pricing': typeof appPricingIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/logout': typeof AuthLogoutIndexRoute
  '/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse/$id': typeof appAnalyseIdRoute
  '/verify/$token': typeof appVerifyTokenRoute
  '/pricing': typeof appPricingIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/logout': typeof AuthLogoutIndexRoute
  '/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/(app)/analyse/$id': typeof appAnalyseIdRoute
  '/(app)/verify/$token': typeof appVerifyTokenRoute
  '/(app)/pricing/': typeof appPricingIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/logout/': typeof AuthLogoutIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse/$id'
    | '/verify/$token'
    | '/pricing'
    | '/login'
    | '/logout'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse/$id'
    | '/verify/$token'
    | '/pricing'
    | '/login'
    | '/logout'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/(app)/analyse/$id'
    | '/(app)/verify/$token'
    | '/(app)/pricing/'
    | '/_auth/login/'
    | '/_auth/logout/'
    | '/_auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  appAnalyseIdRoute: typeof appAnalyseIdRoute
  appVerifyTokenRoute: typeof appVerifyTokenRoute
  appPricingIndexRoute: typeof appPricingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/logout/': {
      id: '/_auth/logout/'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AuthLogoutIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/pricing/': {
      id: '/(app)/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof appPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/verify/$token': {
      id: '/(app)/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof appVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/analyse/$id': {
      id: '/(app)/analyse/$id'
      path: '/analyse/$id'
      fullPath: '/analyse/$id'
      preLoaderRoute: typeof appAnalyseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthLogoutIndexRoute: typeof AuthLogoutIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthLogoutIndexRoute: AuthLogoutIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  appAnalyseIdRoute: appAnalyseIdRoute,
  appVerifyTokenRoute: appVerifyTokenRoute,
  appPricingIndexRoute: appPricingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
