// This file was automatically generated by generate-env-types.js based on .env.template.

export type EnvironmentVariables = {
  VITE_NODE_ENV: string
  VITE_API_URL: string
  VITE_FRONTEND_URL: string
}

export const ENV_NAMES = [
  'VITE_NODE_ENV',
  'VITE_API_URL',
  'VITE_FRONTEND_URL',
] as const

