// This file was automatically generated by generate-env-types.js based on .env.template.

export type IEnvironmentVariables = {
  NODE_ENV: string
  PORT: string
  OPENAI_API_KEY: string
  FRONTEND_URL: string
  JWT_SECRET: string
  JWT_REFRESH_SECRET: string
  SMTP_HOST: string
  SMTP_PORT: string
  SMTP_USER: string
  SMTP_PASS: string
}

export const ENV_NAMES = [
  'NODE_ENV',
  'PORT',
  'OPENAI_API_KEY',
  'FRONTEND_URL',
  'JWT_SECRET',
  'JWT_REFRESH_SECRET',
  'SMTP_HOST',
  'SMTP_PORT',
  'SMTP_USER',
  'SMTP_PASS',
] as const

